function Inp_Truncated_Octahedron (bigMaterialArray, materials, mat_inf, targetFrequency, nmat, model, F_matrix, radius, nEle, directory, filename)
    
    poissonRatio = 0.35;
    density = 1;
    
    %Loading
    % loadedLoading = load(fullfile(directory, 'F.mat'));
    % F_matrix = loadedLoading.F;
    %should be modified
    x_master = [4;0;0];
    y_master = [0;4;0];
    z_master = [0;0;4];

    % Define the input file path
    ElSetFilePath = [directory,'Truncated_Octahedron_ElementSets.txt'];
    NodeSetFilePath = [directory,'Truncated_Octahedron_NodeSets.txt'];
    EqFilePath = [directory,'Truncated_Octahedron_Equations.txt'];

    % Open the input file for reading
    fid2 = fopen(ElSetFilePath, 'r');
    fid3 = fopen(NodeSetFilePath, 'r');
    fid4 = fopen(EqFilePath, 'r');

    fid1 = fopen([directory, filename,'.inp'],'w');
    fprintf(fid1,'%s\n', '*Heading');
    fprintf(fid1,'%s\n', '** Job name: delete_nodes_truncatedOctahedron Model name: Model-1');
    fprintf(fid1,'%s\n', '** Generated by: Abaqus/CAE 2025');
    fprintf(fid1,'%s\n', '*Preprint, echo=NO, model=NO, history=NO, contact=NO');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** PARTS ');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '*Part, name=Part-1 ');
    fprintf(fid1,'%s\n', '*End Part ');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** ASSEMBLY ');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '*Assembly, name=Assembly ');
    fprintf(fid1,'%s\n', '**   ');
    fprintf(fid1,'%s\n', '*Instance, name=Part-1-1, part=Part-1');
    fprintf(fid1,'%s\n', '*Node');
    % fprintf(fid1,'%s\n', '      1,        0.625,         0.25,          0.5');
    % fprintf(fid1,'%s\n', '      2,         0.75,        0.375,          0.5');
    % fprintf(fid1,'%s\n', '      3,         0.75,          0.5,        0.625');
    % fprintf(fid1,'%s\n', '      4,        0.625,          0.5,         0.75');
    % fprintf(fid1,'%s\n', '      5,          0.5,        0.375,         0.75');
    % fprintf(fid1,'%s\n', '      6,          0.5,         0.25,        0.625');
    % fprintf(fid1,'%s\n', '      7,        0.375,         0.25,          0.5');
    % fprintf(fid1,'%s\n', '      8,          0.5,         0.25,        0.375');
    % fprintf(fid1,'%s\n', '      9,          0.5,        0.375,         0.25');
    % fprintf(fid1,'%s\n', '     10,        0.625,          0.5,         0.25');
    % fprintf(fid1,'%s\n', '     11,         0.75,          0.5,        0.375');
    % fprintf(fid1,'%s\n', '     12,         0.75,        0.625,          0.5');
    % fprintf(fid1,'%s\n', '     13,          0.5,        0.625,         0.75');
    % fprintf(fid1,'%s\n', '     14,          0.5,         0.75,        0.625');
    % fprintf(fid1,'%s\n', '     15,        0.625,         0.75,          0.5');
    % fprintf(fid1,'%s\n', '     16,        0.375,          0.5,         0.75');
    % fprintf(fid1,'%s\n', '     17,         0.25,        0.375,          0.5');
    % fprintf(fid1,'%s\n', '     18,        0.375,          0.5,         0.25');
    % fprintf(fid1,'%s\n', '     19,          0.5,        0.625,         0.25');
    % fprintf(fid1,'%s\n', '     20,          0.5,         0.75,        0.375');
    % fprintf(fid1,'%s\n', '     21,        0.375,         0.75,          0.5');
    % fprintf(fid1,'%s\n', '     22,         0.25,          0.5,        0.625');
    % fprintf(fid1,'%s\n', '     23,         0.25,          0.5,        0.375');
    % fprintf(fid1,'%s\n', '     24,         0.25,        0.625,          0.5');

    % fprintf(fid1,'%s\n', '           1,   0.75,   0.0,   0.5');
    % fprintf(fid1,'%s\n', '           2,   1.0,   0.25,   0.5');
    % fprintf(fid1,'%s\n', '           3,   1.0,   0.5,   0.75');
    % fprintf(fid1,'%s\n', '           4,   0.75,   0.5,   1.0');
    % fprintf(fid1,'%s\n', '           5,   0.5,   0.25,   1.0');
    % fprintf(fid1,'%s\n', '           6,   0.5,   0.0,   0.75');
    % fprintf(fid1,'%s\n', '           7,   0.25,   0.0,   0.5');
    % fprintf(fid1,'%s\n', '           8,   0.5,   0.0,   0.25');
    % fprintf(fid1,'%s\n', '           9,   0.5,   0.25,   0.0');
    % fprintf(fid1,'%s\n', '          10,   0.75,   0.5,   0.0');
    % fprintf(fid1,'%s\n', '          11,   1.0,   0.5,   0.25');
    % fprintf(fid1,'%s\n', '          12,   1.0,   0.75,   0.5');
    % fprintf(fid1,'%s\n', '          13,   0.5,   0.75,   1.0');
    % fprintf(fid1,'%s\n', '          14,   0.5,   1.0,   0.75');
    % fprintf(fid1,'%s\n', '          15,   0.75,   1.0,   0.5');
    % fprintf(fid1,'%s\n', '          16,   0.25,   0.5,   1.0');
    % fprintf(fid1,'%s\n', '          17,   0.0,   0.25,   0.5');
    % fprintf(fid1,'%s\n', '          18,   0.25,   0.5,   0.0');
    % fprintf(fid1,'%s\n', '          19,   0.5,   0.75,   0.0');
    % fprintf(fid1,'%s\n', '          20,   0.5,   1.0,   0.25');
    % fprintf(fid1,'%s\n', '          21,   0.25,   1.0,   0.5');
    % fprintf(fid1,'%s\n', '          22,   0.0,   0.5,   0.75');
    % fprintf(fid1,'%s\n', '          23,   0.0,   0.5,   0.25');
    % fprintf(fid1,'%s\n', '          24,   0.0,   0.75,   0.5');


    fprintf(fid1,'%s\n', '           1,    3.0,    0.0,    2.0');
    fprintf(fid1,'%s\n', '           2,    4.0,    1.0,    2.0');
    fprintf(fid1,'%s\n', '           3,    4.0,    2.0,    3.0');
    fprintf(fid1,'%s\n', '           4,    3.0,    2.0,    4.0');
    fprintf(fid1,'%s\n', '           5,    2.0,    1.0,    4.0');
    fprintf(fid1,'%s\n', '           6,    2.0,    0.0,    3.0');
    fprintf(fid1,'%s\n', '           7,    1.0,    0.0,    2.0');
    fprintf(fid1,'%s\n', '           8,    2.0,    0.0,    1.0');
    fprintf(fid1,'%s\n', '           9,    2.0,    1.0,    0.0');
    fprintf(fid1,'%s\n', '          10,    3.0,    2.0,    0.0');
    fprintf(fid1,'%s\n', '          11,    4.0,    2.0,    1.0');
    fprintf(fid1,'%s\n', '          12,    4.0,    3.0,    2.0');
    fprintf(fid1,'%s\n', '          13,    2.0,    3.0,    4.0');
    fprintf(fid1,'%s\n', '          14,    2.0,    4.0,    3.0');
    fprintf(fid1,'%s\n', '          15,    3.0,    4.0,    2.0');
    fprintf(fid1,'%s\n', '          16,    1.0,    2.0,    4.0');
    fprintf(fid1,'%s\n', '          17,    0.0,    1.0,    2.0');
    fprintf(fid1,'%s\n', '          18,    1.0,    2.0,    0.0');
    fprintf(fid1,'%s\n', '          19,    2.0,    3.0,    0.0');
    fprintf(fid1,'%s\n', '          20,    2.0,    4.0,    1.0');
    fprintf(fid1,'%s\n', '          21,    1.0,    4.0,    2.0');
    fprintf(fid1,'%s\n', '          22,    0.0,    2.0,    3.0');
    fprintf(fid1,'%s\n', '          23,    0.0,    2.0,    1.0');
    fprintf(fid1,'%s\n', '          24,    0.0,    3.0,    2.0');

    if strcmp(model, '3DTruss')
        fprintf(fid1,'%s\n', '*Element, type=T3D2');
    elseif strcmp(model, '3DBeam')
        fprintf(fid1,'%s\n', '*Element, type=B31');
    end

    fprintf(fid1,'%s\n', '1, 1, 2');
    fprintf(fid1,'%s\n', '2, 2, 3');
    fprintf(fid1,'%s\n', '3, 3, 4');
    fprintf(fid1,'%s\n', '4, 4, 5');
    fprintf(fid1,'%s\n', '5, 6, 5');
    fprintf(fid1,'%s\n', '6, 7, 6');
    fprintf(fid1,'%s\n', '7, 7, 8');
    fprintf(fid1,'%s\n', '8, 8, 9');
    fprintf(fid1,'%s\n', '9,  9, 10');
    fprintf(fid1,'%s\n', '10, 10, 11');
    fprintf(fid1,'%s\n', '11, 11,  2');
    fprintf(fid1,'%s\n', '12, 1, 6');
    fprintf(fid1,'%s\n', '13, 8, 1');
    fprintf(fid1,'%s\n', '14,  3, 12');
    fprintf(fid1,'%s\n', '15, 13,  4');
    fprintf(fid1,'%s\n', '16, 14, 13');
    fprintf(fid1,'%s\n', '17, 14, 15');
    fprintf(fid1,'%s\n', '18, 15, 12');
    fprintf(fid1,'%s\n', '19,  5, 16');
    fprintf(fid1,'%s\n', '20,  7, 17');
    fprintf(fid1,'%s\n', '21, 18,  9');
    fprintf(fid1,'%s\n', '22, 19, 18');
    fprintf(fid1,'%s\n', '23, 20, 19');
    fprintf(fid1,'%s\n', '24, 20, 21');
    fprintf(fid1,'%s\n', '25, 21, 14');
    fprintf(fid1,'%s\n', '26, 10, 19');
    fprintf(fid1,'%s\n', '27, 12, 11');
    fprintf(fid1,'%s\n', '28, 16, 13');
    fprintf(fid1,'%s\n', '29, 15, 20');
    fprintf(fid1,'%s\n', '30, 16, 22');
    fprintf(fid1,'%s\n', '31, 22, 17');
    fprintf(fid1,'%s\n', '32, 18, 23');
    fprintf(fid1,'%s\n', '33, 21, 24');
    fprintf(fid1,'%s\n', '34, 24, 22');
    fprintf(fid1,'%s\n', '35, 23, 24');
    fprintf(fid1,'%s\n', '36, 23, 17');

    % Read the element sets
    while ~feof(fid2)
        line = fgetl(fid2);  % Read a line from the input file
        if ischar(line)      % Check if the line was read successfully
            fprintf(fid1, '%s\n', line);  % Write the line to the output file
        end
    end

%%
    % Initialize a cell array to store locations for each unique material
    UniqueMaterials = unique(bigMaterialArray);
    
    
    if strcmp(model, '3DTruss')
        for i=1:nEle
            fprintf(fid1,'%s\n', ['** Section: Section-', num2str(i)]);
            fprintf(fid1,'%s\n', ['*Solid Section, elset=Set', num2str(i), ', material=Material-', num2str(bigMaterialArray(i))]);
            fprintf(fid1,'%s\n', [num2str((pi*radius^2)),',']);
        end
    elseif strcmp(model, '3DBeam')
        for i=1:nEle
            fprintf(fid1,'%s\n', ['** Section: Section-', num2str(i), '  Profile: Profile-1']);
            fprintf(fid1,'%s\n', ['*Beam Section, elset=Set', num2str(i), ', material=Material-', num2str(bigMaterialArray(i)), ', temperature=GRADIENTS, section=CIRC']);
            fprintf(fid1,'%s\n', [num2str(radius),',']);
            fprintf(fid1,'%s\n', '0.,0.,-1.');
        end
    end

    % Read the node sets
    while ~feof(fid3)
        line = fgetl(fid3);  % Read a line from the input file
        if ischar(line)      % Check if the line was read successfully
            fprintf(fid1, '%s\n', line);  % Write the line to the output file
        end
    end

    % load equations for applying priodicity

    while ~feof(fid4)
        line = fgetl(fid4);  % Read a line from the additional file
        if ischar(line)      % Check if the line was read successfully
            fprintf(fid1, '%s\n', line);  % Write the line to the output file
        end
    end
    fprintf(fid1,'%s\n', '*End Assembly');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** MATERIALS');
    fprintf(fid1,'%s\n', '** ');

    %Create materials
    for i=1:numel(UniqueMaterials)
        fprintf(fid1,'%s\n', ['*Material, name=MATERIAL-',num2str(UniqueMaterials(i))]);
        fprintf(fid1,'%s\n', '*Density');
        fprintf(fid1,'%s\n', [num2str(density),',']);

        MasterCurveData = materials(UniqueMaterials(i),:);
        materialNumber = mod(UniqueMaterials(i), nmat);
        if materialNumber == 0
            materialNumber = nmat;
        end

        [ViscoelasticTable, Young]=TabularViscoelastic(MasterCurveData(:,1), complex(MasterCurveData(:,2), MasterCurveData(:,3)), poissonRatio, mat_inf(materialNumber,:));

        %make a file to save the material data for the ones that are used in the code
        fprintf(fid1,'%s\n', '*Elastic, moduli=LONG TERM');
        fprintf(fid1,'%s\n', [num2str(Young),', ',num2str(poissonRatio)]);
        fprintf(fid1,'%s\n', '*Viscoelastic, frequency=TABULAR');

        [numRows, numCols] = size(ViscoelasticTable);
        formatSpec = repmat('%e, ', 1, numCols); % Use '%e' for scientific notation
        formatSpec = [formatSpec(1:end-2), '\n']; % Remove the last comma and add a newline

        for rowNumber = 1:numRows
            fprintf(fid1, formatSpec, ViscoelasticTable(rowNumber, :));
        end

    end

    fprintf(fid1,'%s\n', '** ----------------------------------------------------------------');
    fprintf(fid1,'%s\n', '**');
    fprintf(fid1,'%s\n', '** STEP: Step-1');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '*Step, name=Step-1, nlgeom=NO, perturbation');
    fprintf(fid1,'%s\n', '*Steady State Dynamics, direct, friction damping=NO');
    fprintf(fid1,'%s\n', [num2str(targetFrequency),', ', num2str(targetFrequency+1), ', 2,']);

    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** BOUNDARY CONDITIONS');
    fprintf(fid1,'%s\n', '** ');

    %loading with deformation gradient tensor F
    u_masterx = (F_matrix - eye(3))*x_master;
    u_mastery = (F_matrix - eye(3))*y_master;
    u_masterz = (F_matrix - eye(3))*z_master;

    BC_number = 0;

    BC_number = BC_number + 1;
    fprintf(fid1,'%s\n', ['** Name: BC-',num2str(BC_number),' Type: Displacement/Rotation']);
    fprintf(fid1,'%s\n', '*Boundary, real');
    for i = 1:length(u_masterx)
        fprintf(fid1, '%s\n', ['MasterX, ',num2str(i),', ', num2str(i),', ', num2str(u_masterx(i))]);
    end

    BC_number = BC_number + 1;
    fprintf(fid1,'%s\n', ['** Name: BC-',num2str(BC_number),' Type: Displacement/Rotation']);
    fprintf(fid1,'%s\n', '*Boundary, real');
    for i = 1:length(u_mastery)
        fprintf(fid1, '%s\n', ['MasterY, ',num2str(i),', ', num2str(i),', ', num2str(u_mastery(i))]);
    end

    BC_number = BC_number + 1;
    fprintf(fid1,'%s\n', ['** Name: BC-',num2str(BC_number),' Type: Displacement/Rotation']);
    fprintf(fid1,'%s\n', '*Boundary, real');
    for i = 1:length(u_masterz)
        fprintf(fid1, '%s\n', ['MasterZ, ',num2str(i),', ', num2str(i),', ', num2str(u_masterz(i))]);
    end

    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** OUTPUT REQUESTS');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** FIELD OUTPUT: F-Output-1');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '*Output, field');
    fprintf(fid1,'%s\n', '*Node Output, variable=PRESELECT');
    fprintf(fid1,'%s\n', '*Element Output, directions=YES');
    fprintf(fid1,'%s\n', 'ELEDEN, ELEN, ENER, LE, S');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '** HISTORY OUTPUT: H-Output-1');
    fprintf(fid1,'%s\n', '** ');
    fprintf(fid1,'%s\n', '*Output, history');
    fprintf(fid1,'%s\n', '*Energy Output, variable=ALL');
    fprintf(fid1,'%s\n', '*End Step');

    fclose(fid1);
    fclose(fid2);
    fclose(fid3);
end